# Generated by Django 3.1.3 on 2020-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('R', 'reabilitation'), ('P', 'prosthesis'), ('E', 'exosceletion'), ('A', 'Accessories')], default='prosthesis', max_length=20)),
                ('img', models.ImageField(default='noimage.jpg', upload_to='product_image')),
            ],
        ),
    ]
